# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "nord"

# Site Settings
locale                   : "en-US"
title                    : "Wii Guide"
title_separator          : "-"
name                     : "RiiConnect24"
description              : "Wii modding guide"
url                      : "https://wii.guide" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
enforce_ssl              : "wii.guide"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "RiiConnect24/Wii-Guide" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification : NJHNJQvHO4NNbW_2IYtDhRIfX5-4kUpwkxsmVfM7S34
bing_site_verification   : 229FBDF9FE2F1A36CEDFAB9F171C6A4E
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "RiiConnect24"
facebook:
  username               : "RiiConnect24"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-72766480-5"


# Site Author
author:
  name             : "RiiConnect24"
  avatar           : "bio-photo.png"
  bio              : "WiiConnect24 replacement"
  location         : "United States"
  email            : "support@riiconnect24.net"
  uri              : "https://rc24.xyz"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "RiiConnect24"
  foursquare       :
  github           : "RiiConnect24"
  google_plus      : "RiiConnect24"
  keybase          :
  instagram        : "RiiConnect24"
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : "RiiConnect24"
  vine             :
  weibo            :
  xing             :
  youtube          : "RiiConnect24"


# Reading Files
include:
 - .htaccess
 - _pages
 - _pages/en_US
 - _pages/es_MX
 - _pages/fr_FR
 - _pages/it_IT
 - _pages/pl_PL
exclude: [
  "*.sublime-project",
  "*.sublime-workspace",
  vendor,
  .asset-cache,
  .bundle,
  .jekyll-assets-cache,
  .sass-cache,
  assets/js/plugins,
  assets/js/_main.js,
  assets/js/vendor,
  Capfile,
  CHANGELOG,
  config,
  Gemfile,
  Gruntfile.js,
  gulpfile.js,
  LICENSE,
  log,
  node_modules,
  package.json,
  Rakefile,
  README,
  tmp,
  _pages/af_ZA,
  _pages/ar_SA,
  _pages/ca_ES,
  _pages/cs_CZ,
  _pages/da_DK,
  # _pages/de_DE,
  _pages/el_GR,
  _pages/en_PT,
  # _pages/en_US,
  _pages/es_EM,
  # _pages/es_ES,
  # _pages/fi_FI,
  # _pages/fr_FR,
  # _pages/he_IL,
  _pages/hu_HU,
  _pages/id_ID,
  # _pages/it_IT,
  _pages/ja_JP,
  _pages/ko_KR,
  _pages/ms_MY,
  _pages/no_NO,
  _pages/nl_NL,
  # _pages/pl_PL,
  # _pages/pt_BR,
  _pages/pt_PT,
  # _pages/ro_RO,
  # _pages/ru_RU,
  _pages/sr_SP,
  _pages/sv_SE,
  _pages/th_TH,
  _pages/tr_TR,
  _pages/uk_UA,
  _pages/vi_VN,
  _pages/zh_CN,
  # _pages/zh_TW,
]

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar: true
  - scope:
      path: "_pages/en_US"
      type: pages
    values:
      permalink: /:basename:output_ext
      lang: en
  - scope:
      path: "_pages/es_MX"
      type: pages
    values:
      permalink: /es_MX/:basename:output_ext
      lang: es
  - scope:
      path: "_pages/fr_FR"
      type: pages
    values:
      permalink: /fr_FR/:basename:output_ext
      lang: fr
  - scope:
      path: "_pages/it_IT"
      type: pages
    values:
      permalink: /it_IT/:basename:output_ext
      lang: it
  - scope:
      path: "_pages/pl_PL"
      type: pages
    values:
      permalink: /pl_PL/:basename:output_ext
      lang: pl
  - scope:
      path: "_pages/en_US/home.txt"
      type: pages
    values:
      permalink: /index:output_ext
  - scope:
      path: "_pages/es_MX/home.txt"
      type: pages
    values:
      permalink: /es_MX/index:output_ext
  - scope:
      path: "_pages/fr_FR/home.txt"
      type: pages
    values:
      permalink: /fr_FR/index:output_ext
  - scope:
      path: "_pages/it_IT/home.txt"
      type: pages
    values:
      permalink: /it_IT/index:output_ext
  - scope:
      path: "_pages/pl_PL/home.txt"
      type: pages
    values:
      permalink: /pl_PL/index:output_ext